[package]
description = "A tool for generating bindings for Linux Kernel types"
name = "aya-tool"
publish = false
version = "0.1.0"

authors.workspace = true
edition.workspace = true
homepage.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true

[lints]
workspace = true

[dependencies]
anyhow = { workspace = true, default-features = true }
ar = { workspace = true }
aya-multierror = { path = "../aya-multierror", version = "0.1.0", default-features = false }
bindgen = { workspace = true, default-features = true }
cargo_metadata = { workspace = true }
clap = { workspace = true, default-features = true, features = ["derive"] }
nix = { workspace = true, features = ["fs"] }
tar = { workspace = true }
tempfile = { workspace = true }
thiserror = { workspace = true }
ureq = { workspace = true, default-features = false, features = ["rustls"] }
walkdir = { workspace = true }
xz2 = { workspace = true }
zstd = { workspace = true }
