macro_rules! bpf_file {
    ($($uppercase:ident => $lowercase:literal),* $(,)?) => {
        $(
            pub const $uppercase: &[u8] = aya::include_bytes_aligned!(concat!(env!("OUT_DIR"), "/", $lowercase));
        )*
    };
}

bpf_file!(
    EXT => "ext.bpf.o",
    ITER_TASK => "iter.bpf.o",
    MAIN => "main.bpf.o",
    MULTIMAP_BTF => "multimap-btf.bpf.o",
    RINGBUF_BTF => "ringbuf-btf.bpf.o",
    KSYMS => "ksyms.bpf.o",
    KSYMS_STRONG => "ksyms_strong.bpf.o",
    KSYMS_TYPED_MISSING_VAR => "ksyms_typed_missing_var.bpf.o",
    KSYMS_TYPED_MISSING_KFUNC => "ksyms_typed_missing_kfunc.bpf.o",
    KSYMS_TYPELESS_MISSING => "ksyms_typeless_missing.bpf.o",
    KSYMS_XDP_DEV_BOUND_KFUNC => "ksyms_xdp_dev_bound_kfunc.bpf.o",

    ENUM_SIGNED_32_RELOC_BPF => "enum_signed_32_reloc.bpf.o",
    ENUM_SIGNED_32_RELOC_BTF => "enum_signed_32_reloc.bpf.target.o",
    ENUM_SIGNED_32_CHECKED_VARIANTS_RELOC_BPF => "enum_signed_32_checked_variants_reloc.bpf.o",
    ENUM_SIGNED_32_CHECKED_VARIANTS_RELOC_BTF => "enum_signed_32_checked_variants_reloc.bpf.target.o",
    ENUM_SIGNED_64_RELOC_BPF => "enum_signed_64_reloc.bpf.o",
    ENUM_SIGNED_64_RELOC_BTF => "enum_signed_64_reloc.bpf.target.o",
    ENUM_SIGNED_64_CHECKED_VARIANTS_RELOC_BPF => "enum_signed_64_checked_variants_reloc.bpf.o",
    ENUM_SIGNED_64_CHECKED_VARIANTS_RELOC_BTF => "enum_signed_64_checked_variants_reloc.bpf.target.o",
    ENUM_UNSIGNED_32_RELOC_BPF => "enum_unsigned_32_reloc.bpf.o",
    ENUM_UNSIGNED_32_RELOC_BTF => "enum_unsigned_32_reloc.bpf.target.o",
    ENUM_UNSIGNED_32_CHECKED_VARIANTS_RELOC_BPF => "enum_unsigned_32_checked_variants_reloc.bpf.o",
    ENUM_UNSIGNED_32_CHECKED_VARIANTS_RELOC_BTF => "enum_unsigned_32_checked_variants_reloc.bpf.target.o",
    ENUM_UNSIGNED_64_RELOC_BPF => "enum_unsigned_64_reloc.bpf.o",
    ENUM_UNSIGNED_64_RELOC_BTF => "enum_unsigned_64_reloc.bpf.target.o",
    ENUM_UNSIGNED_64_CHECKED_VARIANTS_RELOC_BPF => "enum_unsigned_64_checked_variants_reloc.bpf.o",
    ENUM_UNSIGNED_64_CHECKED_VARIANTS_RELOC_BTF => "enum_unsigned_64_checked_variants_reloc.bpf.target.o",
    FIELD_RELOC_BPF => "field_reloc.bpf.o",
    FIELD_RELOC_BTF => "field_reloc.bpf.target.o",
    POINTER_RELOC_BPF => "pointer_reloc.bpf.o",
    POINTER_RELOC_BTF => "pointer_reloc.bpf.target.o",
    STRUCT_FLAVORS_RELOC_BPF => "struct_flavors_reloc.bpf.o",
    STRUCT_FLAVORS_RELOC_BTF => "struct_flavors_reloc.bpf.target.o",

    TEXT_64_64_RELOC => "text_64_64_reloc.o",
    VARIABLES_RELOC => "variables_reloc.bpf.o",
    FUNC_INFO_MISSING_CALLEE => "func_info_missing_callee.bpf.o",
    FUNC_INFO_MISSING_PROGRAM => "func_info_missing_program.bpf.o",
    FUNC_INFO_ABSENT => "func_info_absent.bpf.o",

    ARRAY => "array",
    BLOOM_FILTER => "bloom-filter",
    BPF_PROBE_READ => "bpf-probe-read",
    BTF_MAPS_PLAIN => "btf-maps-plain",
    CGROUP_ARRAY => "cgroup-array",
    CGROUP_CONNECT => "cgroup-connect",
    CGROUP_STORAGE => "cgroup-storage",
    CPU_MAP => "cpu-map",
    DEV_MAP => "dev-map",
    FEXIT => "fexit",
    HASH_MAP => "hash-map",
    KPROBE => "kprobe",
    LINEAR_DATA_STRUCTURES => "linear-data-structures",
    LOG => "log",
    LPM_TRIE => "lpm-trie",
    MAP_TEST => "map-test",
    MEMMOVE_TEST => "memmove-test",
    NAME_TEST => "name-test",
    PASS => "pass",
    PER_CPU_ARRAY => "per-cpu-array",
    PERF_EVENT_ARRAY => "perf-event-array",
    PERF_EVENT_BYTE_ARRAY => "perf-event-byte-array",
    PERF_EVENT_BP => "perf-event-bp",
    RAW_TRACEPOINT => "raw-tracepoint",
    RELOCATIONS => "relocations",
    RING_BUF => "ring-buf",
    SIMPLE_PROG => "simple-prog",
    SK_REUSEPORT => "sk-reuseport",
    SOCKET_FILTER => "socket-filter",
    SK_STORAGE => "sk-storage",
    SOCK_HASH => "sock-hash",
    SOCK_MAP => "sock-map",
    STRNCMP => "strncmp",
    TC_CLASSID => "tc-classid",
    TCX => "tcx",
    TEST => "test",
    TEST_RUN => "test-run",
    TWO_PROGS => "two-progs",
    XDP_SEC => "xdp-sec",
    UPROBE_COOKIE => "uprobe-cookie",
    PRINTK_TEST => "printk-test",
    PROG_ARRAY => "prog-array",
    STACK_TRACE => "stack-trace",
    STACK_TRACE_LSM => "stack-trace-lsm",
    BTF_MAP_OF_MAPS => "btf-map-of-maps",
    XSK_MAP => "xsk-map",
    INODE_STORAGE => "inode-storage",
    CGRP_STORAGE => "cgrp-storage",
    UPROBE_MULTI => "uprobe-multi",
);

#[cfg(test)]
mod tests;
