[package]
name = "traffic-monitor"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
log = "0.4"
anyhow = "1.0"

[[example]]
name = "standalone-demo"
path = "examples/standalone-demo.rs"

[dev-dependencies]
tempfile = "3.0"