[package]
name = "integration-ebpf"
publish = false
version = "0.1.0"

authors.workspace = true
edition.workspace = true
homepage.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true

[lints]
workspace = true

[dependencies]
aya-ebpf = { path = "../../ebpf/aya-ebpf" }
aya-log-ebpf = { path = "../../ebpf/aya-log-ebpf" }
ebpf-panic = { path = "../../ebpf-panic" }
integration-common = { path = "../integration-common" }
network-types = { workspace = true }

[build-dependencies]
aya-build = { path = "../../aya-build" }
which = { workspace = true, features = ["real-sys"] }
xtask = { path = "../../xtask" }

[[bin]]
name = "array"
path = "src/array.rs"

[[bin]]
name = "bloom-filter"
path = "src/bloom_filter.rs"

[[bin]]
name = "bpf-probe-read"
path = "src/bpf_probe_read.rs"

[[bin]]
name = "btf-maps-plain"
path = "src/btf_maps_plain.rs"

[[bin]]
name = "cpu-map"
path = "src/cpu_map.rs"

[[bin]]
name = "dev-map"
path = "src/dev_map.rs"

[[bin]]
name = "fexit"
path = "src/fexit.rs"

[[bin]]
name = "hash-map"
path = "src/hash_map.rs"

[[bin]]
name = "kprobe"
path = "src/kprobe.rs"

[[bin]]
name = "linear-data-structures"
path = "src/linear_data_structures.rs"

[[bin]]
name = "log"
path = "src/log.rs"

[[bin]]
name = "lpm-trie"
path = "src/lpm_trie.rs"

[[bin]]
name = "map-test"
path = "src/map_test.rs"

[[bin]]
name = "memmove-test"
path = "src/memmove_test.rs"

[[bin]]
name = "name-test"
path = "src/name_test.rs"

[[bin]]
name = "pass"
path = "src/pass.rs"

[[bin]]
name = "per-cpu-array"
path = "src/per_cpu_array.rs"

[[bin]]
name = "perf-event-array"
path = "src/perf_event_array.rs"

[[bin]]
name = "perf-event-byte-array"
path = "src/perf_event_byte_array.rs"

[[bin]]
name = "raw-tracepoint"
path = "src/raw_tracepoint.rs"

[[bin]]
name = "relocations"
path = "src/relocations.rs"

[[bin]]
name = "ring-buf"
path = "src/ring_buf.rs"

[[bin]]
name = "sk-storage"
path = "src/sk_storage.rs"

[[bin]]
name = "sock-hash"
path = "src/sock_hash.rs"

[[bin]]
name = "sock-map"
path = "src/sock_map.rs"

[[bin]]
name = "simple-prog"
path = "src/simple_prog.rs"

[[bin]]
name = "sk-reuseport"
path = "src/sk_reuseport.rs"

[[bin]]
name = "socket-filter"
path = "src/socket_filter.rs"

[[bin]]
name = "strncmp"
path = "src/strncmp.rs"

[[bin]]
name = "tc-classid"
path = "src/tc_classid.rs"

[[bin]]
name = "tcx"
path = "src/tcx.rs"

[[bin]]
name = "test"
path = "src/test.rs"

[[bin]]
name = "test-run"
path = "src/test_run.rs"

[[bin]]
name = "two-progs"
path = "src/two_progs.rs"

[[bin]]
name = "xdp-sec"
path = "src/xdp_sec.rs"

[[bin]]
name = "uprobe-cookie"
path = "src/uprobe_cookie.rs"

[[bin]]
name = "uprobe-multi"
path = "src/uprobe_multi.rs"

[[bin]]
name = "perf-event-bp"
path = "src/perf_event_bp.rs"

[[bin]]
name = "printk-test"
path = "src/printk_test.rs"

[[bin]]
name = "prog-array"
path = "src/prog_array.rs"

[[bin]]
name = "stack-trace"
path = "src/stack_trace.rs"

[[bin]]
name = "stack-trace-lsm"
path = "src/stack_trace_lsm.rs"

[[bin]]
name = "btf-map-of-maps"
path = "src/btf_map_of_maps.rs"

[[bin]]
name = "xsk-map"
path = "src/xsk_map.rs"

[[bin]]
name = "cgroup-array"
path = "src/cgroup_array.rs"

[[bin]]
name = "cgroup-connect"
path = "src/cgroup_connect.rs"

[[bin]]
name = "cgroup-storage"
path = "src/cgroup_storage.rs"

[[bin]]
name = "inode-storage"
path = "src/inode_storage.rs"

[[bin]]
name = "cgrp-storage"
path = "src/cgrp_storage.rs"

[[bin]]
name = "syscall-args"
path = "src/syscall_args.rs"
