[package]
name = "ebpf-panic"
publish = false
version = "1.0.0"

authors.workspace = true
edition.workspace = true
homepage.workspace = true
license.workspace = true
repository.workspace = true

[dev-dependencies]
aya-ebpf = { path = "../ebpf/aya-ebpf" }
