package(default_visibility = ["//visibility:public"])

exports_files([
    "aya_aarch64.config",
    "aya_x86_64.config",
])

alias(
    name = "aya_kernel",
    actual = select({
        "@platforms//cpu:aarch64": "@aya_aarch64_kernel//:kernel",
        "@platforms//cpu:x86_64": "@aya_x86_64_kernel//:kernel",
    }),
)

alias(
    name = "aya_kernel_config",
    actual = select({
        "@platforms//cpu:aarch64": "@aya_aarch64_kernel//:config",
        "@platforms//cpu:x86_64": "@aya_x86_64_kernel//:config",
    }),
)

alias(
    name = "aya_kernel_system_map",
    actual = select({
        "@platforms//cpu:aarch64": "@aya_aarch64_kernel//:system_map",
        "@platforms//cpu:x86_64": "@aya_x86_64_kernel//:system_map",
    }),
)
